---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aap-instance
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: ansible-automation-platform
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/lab-content/ansible-aap/instance/overlays/default
    repoURL: https://github.com/tosin2013/rhel-edge-CaC.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true