apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  name: devspaces
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: devspaces-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: deploy/lab-content/operators/devspaces
    repoURL: https://github.com/tosin2013/rhel-edge-CaC.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true