name: Configure Ansible Navgiator workflow
on:
  workflow_dispatch:
    inputs:
      hostname:
        description: 'hostname'
        required: false
        default: hostname
jobs:
  say_hello:
    runs-on: configure-ansible-navigator
    timeout-minutes: 45
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ inputs.hostname }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: | 
          if [ -d "$HOME/rhel-edge-CaC" ]; then
            cd $HOME/rhel-edge-CaC
            git config pull.rebase false
            git pull
          else
            cd $HOME/rhel-edge-CaC
            git clone https://github.com/tosin2013/rhel-edge-CaC.git
          fi
          deploy/controller-casc-cd/configure-rhel8.7.sh
