name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'USERNAME'
        required: true
        default: 'admin'
      hostname:
        description: 'hostname'
        required: false
        default: hostname
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ::add-mask::${{ inputs.hostname }}
        username: ${{ inputs.username }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: whoami