name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'USERNAME'
        required: true
        default: 'admin'
      hostname:
        description: 'hostname'
        required: false
        default: hostname
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello ${{ inputs.username }}"
        echo "::add-mask::${{ inputs.hostname }}"