name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'USERNAME'
        required: true
        default: 'Mona the Octocat'
      password:
        description: 'PASSWORD'
        required: false
        default: P@s$w0Rd'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello ${{ inputs.username }}"
        echo "- in ${{ inputs.password }}"